spring.application.name=biblioteca-sistema
server.port=8080

# Caminho do arquivo do banco SQLite
biblioteca.db.path=biblioteca.db

# Thymeleaf: desabilita cache em desenvolvimento
spring.thymeleaf.cache=false
